### PR TITLE
Normalize the formatting of mentor details

### PR DESCRIPTION
**Pull request by sorenmortensen**
Including capitalisation, punctuation, list separators, and consistent link formatting.

Signed-off-by: Søren Mortensen <soren@neros.dev>

### CODE REVIEW

**Comment by yaahc** [comment]
Can we default to hyphens after the first : in the line? I initially tried it with double : and thought it looked bad personally. So Twitter - etc., but making the hyphens consistent everywhere is good imo

**Comment by sorenmortensen** [comment]
Alternatively, we could do it with brackets:

> ### Søren Mortensen - [@sorenmortensen](https://github.com/sorenmortensen)
> * **Pronouns**: he/him
> * **Contact**: Twitter ([@nerosnm](https://twitter.com/nerosnm)) or email ([soren@neros.dev](mailto:soren@neros.dev))
> * **Spoken Languages**: English
> * **Topics**: Beginners/the basics, developer tools, CLI, Rust–Swift/Objective-C interop

**Comment by yaahc** [comment]
You're the freaking best, actually can you add back the emphasis on Arabic for shady? I think its important to be able to highlight which language is your first language. We should probably emphasis them all, I'll add it to the template to bold your first language so people know if they're speaking to you in a second language or not. I think it will help with misunderstandings from miscommunication.

I'll also ask the other mentors what their first language is so I can emphasis it for them.

**Comment by yaahc** [comment]
brackets are great :+1:

**Comment by sorenmortensen** [comment]
Sure, agree with the emphasis. Perhaps we could try it with italics instead? The bold seems to blend in a lot:

> * **Spoken Languages**: **Arabic**, English
> * **Spoken Languages**: _Arabic_, English

**Comment by yaahc** [comment]
Italics are fine.

**Comment by yaahc** [comment]
emphasise english for Lucio and Dutch for mara

**Comment by sorenmortensen** [comment]
What's our base case? I'm assuming we don't emphasise languages that are in a one-element list?

**Comment by yaahc** [comment]
Yea... I think single language we can just leave be.

**Comment by yaahc** [comment]
You even hit up the template. You're the freaking best :heart:

**Comment by yaahc** [comment]
ty so much for helping with this, definitely helping me stay whelmed.

**Comment by sorenmortensen** [comment]
No problem at all! I'm ready for this to merge if you are.

**Pull request merged**
