### PR TITLE
Add Nikolai

### LINKED ISSUE #6: Cursed Code Counsellor
* **Preferred Name**: Nikolai Vazquez

* **Github Username or equivalent handle**: nvzqz

* **Pronouns**: he/him/his

* **Contact**: nikvzqz@gmail.com

* **Spoken Languages**: English, Spanish, German

* **Topics**: Learning Rust from nothing or experienced newcomers

* **Additional resources**: I maintain the Static Assertions crate and so I'd be happy to teach people how it works

### PR DESCRIPTION
**Pull request by yaahc**
closes #6

### CODE REVIEW

**Comment by sorenmortensen** [comment]
I can update the formatting on this if you like

**Comment by yaahc** [comment]
:+1:

**Comment by sorenmortensen** [comment]
Hold on, don't merge until formatting changes land please

**Comment by yaahc** [comment]
ACK

**Pull request merged**
