### PR TITLE
Add seun

### LINKED ISSUE #83: Seun
Preferred Name: Seun.

Github Handle: https://github.com/joshuaaminu

Pronouns: He/him

Contact: https://wa.me/2348170321148, Twitter ([@seun_ja](https://twitter.com/seun_ja))

Spoken Languages: English.

Topics: Rust generally, as a beginner

Additional Resources: Any other learning resources that you maintain that you would like to share.

### PR DESCRIPTION
**Pull request by yaahc**
closes #83

### CODE REVIEW

**Comment by yaahc** [comment]
@joshuaaminu lmk if this looks good

**Comment by yaahc** [comment]
It looks like the github profile you posted isn't valid. should I update it to be https://github.com/seun-ja? @seun-ja

**Comment by seun-ja** [comment]
Yes. But I made a mistake. I thought the group was for mentees

**Comment by yaahc** [comment]
Ooh! yes, it is for mentees but mentees don't apply to the mentor list, you just go ahead and contact people already on the list :sweat_smile: 

I'll go ahead and close this in that case.

**Pull request closed without merging**
